# Change these first
owner: dohnutt # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: dohnutt
sites:
  - name: dohnutt.com
    url: https://dohnutt.com
  - name: ericmoss.ca
    url: https://ericmoss.ca
  - name: Dohnet on Plex
    url: $SITE_PLEX_DOHNET
    slug: plex
  - name: Dohnet services
    url: $SITE_TV_DOHNUTT

status-website:
  cname: status.dohnutt.com
  #baseUrl: /your-repo-name
  robotsText: "User-agent: * \n Disallow: /"
  customHeadHtml: '<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">'
  themeUrl: https://status.dohnutt.com/theme.css
  logoUrl: https://status.dohnutt.com/apple-donut-96x96.png
  name: Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
